### PR TITLE
Fix time prefix to be tm/

### LINKED ISSUE #123: Change time prefix to be consistent throughout code

### PR DESCRIPTION
**Pull request by meglwhy**
Closes #123

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/EditSessionCommandParser.java [hunk 1]
```diff
@@ -17,12 +22,6 @@ public class EditSessionCommandParser implements Parser<EditSessionCommand> {
                     + "Example: edit-session id/H000007-2 d/2025-09-27 tm/19:00\n"
                     + "Example with note: edit-session id/H000007-2 d/2025-09-27 tm/19:00 n/Follow-up";
 
-    private static final Prefix PREFIX_ID = new Prefix("id/");
```
Comment (malihahaque) [inline src/main/java/seedu/address/logic/parser/EditSessionCommandParser.java:20]: I like how you made the code more succinct! I will try to extend this to my other command classes
