### PR TITLE
Fix bug in view-household-session

### LINKED ISSUE #134: Fix ViewHouseholdSession Bug
There is a bug where a pair of exceptions are thrown every time ViewHouseholdSession is invoked.

Image

### PR DESCRIPTION
**Pull request by malihahaque**
closes #134

### CODE REVIEW

File: src/main/java/seedu/address/ui/HouseholdListPanel.java [hunk 1]
```diff
@@ -72,12 +72,12 @@ protected void updateItem(Household household, boolean empty) {
...
      */
     public void selectHouseholdById(String householdId) {
-        ObservableList<Household> households = listView.getItems();
+        ObservableList<Household> households = householdListView.getItems();
         for (int i = 0; i < households.size(); i++) {
             Household household = households.get(i);
             if (household.getId().toString().equals(householdId)) {
-                listView.getSelectionModel().clearAndSelect(i);
-                listView.scrollTo(i);
+                householdListView.getSelectionModel().clearAndSelect(i);
```
Comment (MrAsparag00se) [inline src/main/java/seedu/address/ui/HouseholdListPanel.java:79]: Looks good to me, will have to test it out after merging.

**Review by MrAsparag00se — APPROVED** [review]
